pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/pablomunozramirez/MINGESO_1.git']])
                dir("MINGESO_1-main/PEP1MINGESO"){
                    bat "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("MINGESO_1-main/PEP1MINGESO"){
                    bat "mvn test"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("MINGESO_1-main/PEP1MINGESO"){
                    bat "docker build -t 2pablo2/mingeso1 ."
                }
            }
        }
        stage("Push Docker Image"){
            steps{
                dir("MINGESO_1-main/PEP1MINGESO"){
                    withCredentials([string(credentialsId: 'dckrhubpassword', variable: 'dckpass')]){
                        bat "docker login -u 2pablo2 -p ${dckpass}"

                    }
                    bat "docker push 2pablo2/mingeso1"

                }

            }
        }
    }
    post{
        always{
            dir("MINGESO_1-main/PEP1MINGESO"){
                bat "docker logout"
            }
        }
    }
}
